version: '3'
services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbtest
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      -  "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@pg.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    restart: unless-stopped